# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Leaves 1.18.2 Build

on:
  push:
    branches: [ 1.18.2 ]
  pull_request:
    branches: [ 1.18.2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Git Config
      run: |
        git config --global user.email "ci@leavesmc.top"
        git config --global user.name "Leaves CI"
    - name: Apply Patches
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: applyPatches
    - name: Paperclip Jar
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: createReobfPaperclipJar
    - name: Archive Leaves Paperclip
      uses: actions/upload-artifact@v2
      with:
        name: Leaves
        path: build/libs/Leaves-paperclip-1.18.2-R0.1-SNAPSHOT-reobf.jar
